version: '2'
services:

  template-microservice:

    build: .
    image: 'template-microservice'
    container_name: 'template-microservice-container'
    links:
      - dev-mongo
    ports:
      - 8080:8080
    volumes:
      - ./logs:/template_microservice_workdir/logs
    environment:
      - NODE_ENV=testing

  dev-mongo:
    build: ./sandbox/docker-mongodb
    image: djaqua/mongodb:latest
    # used to use frodenas/mongodb:latest
    container_name: "dev-mongo"
    ports:
      - 27017:27017
    volumes:
      - ./logs:/logs

    environment:
      - MONGO_DATA_DIR=/data
      - MONGO_LOG_DIR=/logs

      # djaqua/mongodb specific environment variables
      - MONGODB_USERNAME=janie
      - MONGODB_PASSWORD=BylmOlirt5owEew#
      - MONGODB_DBNAME=template_microservice
