version: '3'
services:

  template_microservice:
    
    
    #  
    build: '.'
    image: 'localhost:5000/template_microservice'
     
    links:
      - mongodb
    ports:
      - 8000:80
    volumes:
      - ./logs:/template_microservice_workdir/logs
    environment:
      - NODE_ENV=development

  
  mongodb:
    image: frodenas/mongodb:latest 
    container_name: "dev-mongo"
    ports: 
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./logs:/data/logs
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs   

      # frodenas/mongodb specific environment variables
      - MONGODB_USERNAME=janie
      - MONGODB_PASSWORD=Erf'Shlipcutieg4
      - MONGODB_DBNAME=template_microservice
