#!/bin/bash

export MICROSERVICE_PROJECT_HOME="$( cd "$( dirname $0 )" && pwd )"
NODEJS_BIN="${MICROSERVICE_PROJECT_HOME}/node_modules/.bin"
PROJECT_BIN="${MICROSERVICE_PROJECT_HOME}/bin"

nvm install  # installs the correct version of NodeJS to run this microservice
npm install  # installs the dependencies for this microservice

test -d logs || mkdir logs
test -d data || mkdir data


export PATH="${PROJECT_BIN}:${NODEJS_BIN}:${PATH}"



